version: '3.8'
services:
  postgres:
    container_name: postgres-bibernate
    image: 'postgres:15.5'
    restart: always
    environment:
      - 'POSTGRES_DB=bibernate'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5434:5432"